# Generated by Django 3.2.15 on 2022-10-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0039_auto_20221018_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='', max_length=200, verbose_name='Адрес доставки'),
            preserve_default=False,
        ),
    ]
