# Generated by Django 3.2.15 on 2022-10-18 23:32

from django.db import migrations


def fill_price_for_old_orders(apps, schema_editor):
    order_item_model = apps.get_model('foodcartapp', 'OrderItems')
    order_items = order_item_model.objects.select_related('product')
    for order_item in order_items.iterator():
        order_item.price = order_item.product.price
        order_item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_orderitems_price'),
    ]

    operations = [
        migrations.RunPython(fill_price_for_old_orders)
    ]
