# Generated by Django 3.2.15 on 2022-10-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20221031_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CARD', 'Картой'), ('CASH', 'Наличными')], db_index=True, max_length=4, verbose_name='Способ оплаты'),
        ),
    ]
